#默认使用配置
spring:
  profiles:
    active: dev
  redis:
    database: 0
    host: 192.168.3.236
    port: 6379
    timeout: 10000
    password: eefa497350617a3c47c5
#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.yuan.erp.entity
  mapperLocations: classpath:mapper/*.xml
  #configuration: mapUnderscoreToCamelCase=true
mapper:
  plugin: tk.mybatis.mapper.generator.MapperPlugin
  Mapper: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
---  #分隔线不能少

#开发配置
spring:
  profiles: dev
  datasource:
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
    url: jdbc:mysql://192.168.3.236:3307/erp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: yuanshuai1995
    password: eefa497350617a3c47c5
    driver-class-name: com.mysql.jdbc.Driver
